FROM python:3.12-slim-bullseye
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY data_micro/requirements.txt .
RUN pip install --no-cache -r /app/requirements.txt
COPY data_micro /app/data_micro
CMD ["python", "-m", "data_micro"]