services:
  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/data:/data
      - ./nats/config/server.conf:/config/server.conf

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      - "31311:31311"  # Порт для доступа к NATS NUI
    volumes:
      - ./nui/db:/db
    depends_on:
      - nats

  # bot:
  #   image: 'vangerm/MaxidomBot:v0.1'
  #   container_name: MaxidomBot
  #   restart: 'unless-stopped'
  #   env_file: './bot/.env'
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   # volumes:
  #   #   - ./bot/loger:/loger
  #   depends_on:
  #     - 'nats-nui'

  # microservice_vk:
  #   image: 'vangerm/maxidom_data_micro:v0.1'
  #   container_name: maxidom_data_micro
  #   restart: 'unless-stopped'
  #   env_file: './microservice_vk/.env'
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   # volumes:
  #   #   - ./microservice_vk/loger:/loger
  #   depends_on:
  #     - 'bot'